version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

python:
  install:
    - method: setuptools
      path: .
      extra_requirements:
        - sphinx_rtd_theme


sphinx:
  configuration: docs/source/conf.py