site_name: Radium Nodes
repo_url: https://github.com/rfletchr/radium_nodes

theme:
  name: material
  palette:
    scheme: slate
    accent: amber
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Welcome: index.md
  - Structure: structure.md
  - Defining Ports and Nodes: definition.md